### ISSUE TITLE
Dask and ESMPy

### ISSUE THREAD

**Issue by bekozi** [JiaweiZhuang/xESMF#1]
This looks like a great project, and I'm looking forward to following its progress! I know the ACME group has been using Dask with ESMPy (https://github.com/ACME-Climate/acme_diags), and I wanted to let you know in case this was something useful to you.

**Comment by JiaweiZhuang** [comment]
Thanks, that's good to know! 

Weirdly, I see both dask and ESMPy in yaml files , but don't really find any use of ESMPy or dask in their python code (acme_diags/acme_diags/).

**Comment by bekozi** [comment]
Ha, that is weird. It must be in the _very_ early stages of development. Anyway, just wanted to bring it to your attention! I'll close the ticket.
