### ISSUE TITLE
Regridding introduces missing values at wraparound longitude

### ISSUE THREAD

**Issue by spencerahill** [JiaweiZhuang/xESMF#10]
See this gist for details: https://gist.github.com/anonymous/7e5dcfc3d84938266ddc1c2159770823

Entirely possible I'm making a silly mistake, but I can't figure it out so far at least.  Thanks in advance for help.

**Comment by JiaweiZhuang** [comment]
Oops, xESMF has some issue with periodic boundary conditions right now. Sorry for the trouble.

There are two quick ways to fix that:
- Use conservative regridding. It uses cell corner information and won't miss any cells.
- Manually extend one more grid point in the longitude direction. For example, let `lon = [-180, -175..., 175, 180]` and use the same data at `-180` and `180`

**Comment by spencerahill** [comment]
Thanks. I will try one or both of these and let you know how it goes.

**Comment by JiaweiZhuang** [comment]
Periodic boundary option is now included in v0.1.1. Just set 
`regridder = xe.Regridder(..., periodic=True)`

The option is used in this [demo](http://xesmf.readthedocs.io/en/latest/Compare_algorithms.html).
