### ISSUE TITLE
Requirements file for notebooks environment

### ISSUE THREAD

**Issue by huard** [JiaweiZhuang/xESMF#100]
Some notebooks require matplotlib, cartopy and possibly others. These should be indicated in a `requirements_doc.txt` file or a conda `environment.yml`.

**Comment by dcherian** [comment]
Eventually it would be nice to have binder capabilities. The env file would be a step toward that.

**Comment by huard** [comment]
- matplotlib
- cartopy
- dask
- cftime

**Comment by dcherian** [comment]
There is already binder capability!
 https://github.com/JiaweiZhuang/xESMF/blob/master/binder/environment.yml ?

**Comment by huard** [comment]
Nice ! Should then probably be updated to ESMPy 8.0.
