### ISSUE TITLE
An error when installing xesmf package

### ISSUE THREAD

**Issue by JiyuanGao** [JiaweiZhuang/xESMF#104]
`(base) C:\Users\JY Gao>pip install xesmf`
`Collecting xesmf`
  `Using cached xesmf-0.3.0.tar.gz (532 kB)`
`ERROR: Could not find a version that satisfies the requirement esmpy (from xesmf) (from versions: none)`
`ERROR: No matching distribution found for esmpy (from xesmf)`

**Comment by zxdawn** [comment]
`esmpy` isn't supported on the Windows system. You can try WSL or docker-miniconda.

Please follow the [installation guide](https://xesmf.readthedocs.io/en/latest/installation.html).

**Comment by roysc** [comment]
I get an identical error when installing this on Linux. Is this package designed to only be installed via conda? `esmpy` is [not on PyPI](https://pypi.org/search/?q=esmpy).
