### ISSUE TITLE
Install instructions to avoid ImportError failing?

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [JiaweiZhuang/xESMF#108]
Aloha xESMF community,

Usage: install on local org's HPC system.
wrt: https://xesmf.readthedocs.io/en/latest/installation.html

I was able to install xESMF following the steps above with `conda install -c conda-forge xesmf` but after setting up that environment it fails the `pytest` with the dreaded: 

> ImportError: Regrid(filename) requires PIO and does not work if ESMF has not been built with MPI support

I've then tried many times to start fresh and run `conda install -c conda-forge xesmf esmpy=7.1.0` but I consistently get:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): failed
```

My `conda` skills are rather average and wondering if there is something obvious I'm doing wrong or if someone could point me in the right direction?

Thanks for the open source efforts on this package!

**Comment by Thomas-Moore-Creative** [comment]
NB -  it seems active development has moved here https://github.com/pangeo-data/xESMF

**Comment by mickaellalande** [comment]
Give a look at this issue: https://github.com/JiaweiZhuang/xESMF/issues/47#issuecomment-665516640: `conda install -c conda-forge esmpy xesmf` should work, otherwise try to install `esmpy` first.
