### ISSUE TITLE
After conda update, problem with cf_xarray: "Receive multiple variables for key 'longitude': ['i', 'lon']"

### ISSUE THREAD

**Issue by eocene** [JiaweiZhuang/xESMF#113]
Hi all,

I'm using raw model output that looks like this:

<img width="790" alt="Screenshot 2021-01-22 at 11 18 04" src="https://user-images.githubusercontent.com/3886887/105484614-807c8180-5ca3-11eb-8f43-776e6ba0e419.png">

And I'm getting this error message returned:

<img width="1013" alt="Screenshot 2021-01-22 at 11 19 23" src="https://user-images.githubusercontent.com/3886887/105484882-f680e880-5ca3-11eb-9fe9-80e31db3b4ad.png">

Everything working fine before I ran conda update.

Does anyone have an idea how to move forward? (instead of just reverting everything to old versions)

Thank you!

**Comment by dcherian** [comment]
can you show `ds.i.attrs` and `ds.lon.attrs`

**Comment by eocene** [comment]
Sure!

<img width="370" alt="Screenshot 2021-01-22 at 14 59 25" src="https://user-images.githubusercontent.com/3886887/105506888-7453ec80-5cc2-11eb-8f52-47f774a81b2f.png">

**Comment by malmans2** [comment]
The latest versions of xesmf have been developed here: https://github.com/pangeo-data/xESMF
You are probably using xesmf 0.5.0 or 0.5.1, and I think you are experiencing this issue: https://github.com/pangeo-data/xESMF/pull/64

You have a few options:
- Downgrade to xesmf<0.5.0 (e.g. `conda install -c conda-forge "xesmf!=0.5.0,!=0.5.1"`)
- The breaking change has been fixed but I don't think it was released yet. You could install from github (e.g., `pip install git+https://github.com/pangeo-data/xESMF.git`)

Alternatively, you have to create the regridder using a dataset with only one latitude/longitude coordinate, where the coordinates are defined by the `standard_name` attribute. For example, if you drop `lon` and `lat` in your dataset, xesmf will use the coordinates named `i` and `j`.

Looks like you already have installed cf_xarray, so for a recap of the cf attributes associated with your dataset:
```python
import cf_xarray
ds.cf.describe()
```

**Comment by eocene** [comment]
Thanks yes, I had fixed it reverting back. Will wait for push to conda before doing update.

Cheers!
