### ISSUE TITLE
Gridding sparse data (fine to coarse)

### ISSUE THREAD

**Issue by NicWayand** [JiaweiZhuang/xESMF#33]
hi @JiaweiZhuang, I am trying to regrid sparse (~1 km) [Ice Bridge data](https://nsidc.org/data/docs/daac/icebridge/evaluation_products/sea-ice-freeboard-snowdepth-thickness-quicklook-index.html) (airborne flight transects) to a coarser 25 km grid, using the new `conservative_normed` method from your [master branch](https://github.com/JiaweiZhuang/xESMF/tree/masking). But I am getting only NaNs out. 

Even if there is only one non-NaN fine cell within a coarse cell, it should assign that only fine cell's value to the coarse cell, correct?

A runable example can be found [here](https://github.com/NicWayand/ESIO/blob/master/notebooks/Test_IB_regrid.ipynb).

**Comment by JiaweiZhuang** [comment]
In your case, getting all NaNs is the expected, default behavior for most algorithms, as explained in https://github.com/JiaweiZhuang/xESMF/issues/22#issuecomment-399280598.

To get rid of NaNs, you need to apply masking like https://github.com/JiaweiZhuang/xESMF/issues/22#issuecomment-410810471. `conservative` vs `conservative_normed` only affects the magnitude of the regridding result, not the occurrence of NaNs.

**Comment by JiaweiZhuang** [comment]
There should be a `ds_fine['mask']` that masks all cells out of your data trajectory (i.e. all NaNs in the input data).

**Comment by NicWayand** [comment]
Ah thanks! I had the `ds_target['mask'] `but forgot the `ds_fine['mask']`.

Now getting non-nan values in the coarse grid as expected:
![image](https://user-images.githubusercontent.com/1117224/45178989-1941fd80-b1cc-11e8-8310-bd750b0bc428.png)

However, now all other coarse cells were set to 0, when **I** would have expected them to be NaN. From past convos I understand this is the expected current behavior. 

Using the add offset, mask > offset, subtract offset, workaround works for now but feels a little hacky. Thanks for all the work on #22!

![image](https://user-images.githubusercontent.com/1117224/45179322-11cf2400-b1cd-11e8-88a1-62bc1bda8f31.png)
