### ISSUE TITLE
Installing Issue: dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by itarec1988** [JiaweiZhuang/xESMF#37]
Hi Jiawei,
I was trying to install xesmf on a MAC and I had the following error:

(base) host210-186:~ jayant$ pip install xesmf
Collecting xesmf
  Downloading https://files.pythonhosted.org/packages/2a/34/b551535704101b7ce4e4cbdeb3806800e860df814d73728e376fdc410a0c/xesmf-0.1.1.tar.gz
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /anaconda3/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /anaconda3/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib

I installed xarray and esmpy previously. Do you have any hints here?

**Comment by JiaweiZhuang** [comment]
Haven't seen this error before! Looks like something wrong with your Mac?

Does installing from source work?
`pip install  git+https://github.com/JiaweiZhuang/xESMF.git`

**Comment by itarec1988** [comment]
Yeah, it's a weird error. Installing from source was not successful. I will try to do everything from scratch again.
Thanks!

**Comment by JiaweiZhuang** [comment]
Closing as no further responses.  Feel free to re-open.
