### ISSUE TITLE
Possibly incorrect terminology in documentation

### ISSUE THREAD

**Issue by JanisGailis** [JiaweiZhuang/xESMF#40]
This is a documentation issue.

I believe you have mixed up the terms 'downsample' and 'upsample' in [documentation](https://xesmf.readthedocs.io/en/latest/Compare_algorithms.html). It is said:
```
When regridding from low-resolution to high-resolution (down-sampling)
```
And:
```
When regridding from high-resolution to low-resolution (up-sampling)
```

But the opposite seems to be the generally accepted definition:
https://en.wikipedia.org/wiki/Decimation_(signal_processing)
https://en.wikipedia.org/wiki/Upsampling

Going from low-res (coarse) grid to high-res (fine) grid increases the sampling rate => 'upsampling'.
Going from high-res (fine) grid to low-res (coarse) grid reduces the sampling rate => 'downsampling'

Let me know if I'm wrong and I have mixed up the terms myself!

**Comment by JiaweiZhuang** [comment]
Good catch!

I should have used "[downscaling](https://en.wikipedia.org/wiki/Downscaling)" instead of "downsampling". The former is a climate modeling term while the latter comes from signal processing. Confusingly, "downscaling" is actually equivalent to "upsampling", both referring to "increasing resolution".

> Downscaling is any procedure to infer high-resolution information from low-resolution variables.

> upsampling can refer to the entire process of increasing the sampling rate of a signal

**Comment by JiaweiZhuang** [comment]
So I decided to avoid using either "downsampling" or "downscaling" in the docs. Simply using "Increasing/Decreasing resolution" should be the least confusing...

Thanks for pointing this out!
