### ISSUE TITLE
esmpy needs GFortran 

### ISSUE THREAD

**Issue by zxdawn** [JiaweiZhuang/xESMF#43]
It's better to mention that [esmpy requires GFortran](https://github.com/ioos/conda-recipes/issues/676#issuecomment-167015494).
Otherwise, someone will get this [error](https://github.com/ioos/conda-recipes/issues/676#issuecomment-166465665).
I'm still [struggling with that](https://github.com/ioos/conda-recipes/issues/676#issuecomment-439601359).

**Comment by JiaweiZhuang** [comment]
Shouldn't gfortran come with conda? Are you trying to compile ESMPy from source code?

**Comment by JiaweiZhuang** [comment]
The error you get might not be a gfortran issue; if gfortran is not working properly then yon won't even be able to install numpy.

I recommend sending the complete error message and your system information to ESMF support (esmf_support@ucar.edu).

**Comment by JiaweiZhuang** [comment]
If your server is using some strange OS, see if you can get Docker/Singularity containers running...

**Comment by zxdawn** [comment]
Maybe it's related to the version of gcc.
My gcc is 4.3.4 which is too old to use `Qt5Agg` rendering.
It's maybe same for the error about ESMF.

I'll try Docker/Singularity containers.
Thank you!

**Comment by zxdawn** [comment]
I tried again with `export LD_LIBRARY_PATH=''` and it works now.

**Comment by JiaweiZhuang** [comment]
> I tried again with `export LD_LIBRARY_PATH=''` and it works now.

If you already have another version of ESMF installed on your system, you might get a conflict like that...
