### ISSUE TITLE
Regrid summed variables

### ISSUE THREAD

**Issue by zxdawn** [JiaweiZhuang/xESMF#44]
I want to regrid `total lightning flashcounts` (TL) generated by `WRF-Chem` from 12 km to 1 degree. `TL` is the sum of flashcounts in each 12 km grid.

I've tried xesmf with `bilinear` or `conservative` method, but both results fails. You can check [notebook1](https://github.com/zxdawn/GEOSChem-python-tutorial/blob/master/Chapter04_regridding_WRFChem_part1.ipynb) and [notebook2](https://github.com/zxdawn/GEOSChem-python-tutorial/blob/master/Chapter05_regridding_WRFChem_part2.ipynb).

Do you have any advice of regridding variables like `TL`?

**Comment by JiaweiZhuang** [comment]
`conservative` works on intensive properties (density-like fields). If you have extensive properties (mass-like), divide by cell area first.

**Comment by JiaweiZhuang** [comment]
Alternatively, `nearest_d2s` conserves extensive properties directly.

**Comment by zxdawn** [comment]
Thank you for your advice! `nearest_d2s` works fine.

By the way, have you tried to calculate the cell area? I can't find package in python to calculate it directly. I used to calculate it by [cal_area.m](https://www.mathworks.com/matlabcentral/fileexchange/59295-calcarea-compute-the-area-of-a-shape-given-a-vector-defining-its-border) with [pymatbridge](https://github.com/arokem/python-matlab-bridge).

**Comment by JiaweiZhuang** [comment]
> `nearest_d2s` works fine.

That's good to know! I would appreciate a reproducible example (code + sample data). `nearest_d2s` is so rarely used so it is nice to show a use case.

> have you tried to calculate the cell area?

See this gist for now: https://gist.github.com/JiaweiZhuang/fc2f860133174523051260817e75a99d

**Comment by zxdawn** [comment]
I've rewritten the regridding prat and you can check [it](https://github.com/zxdawn/GEOSChem-python-tutorial/blob/master/Chapter04_regridding_WRFChem.ipynb).

It looks like `nearest_d2s` and `conservative` get the similar result, while `bilinear` keeps the original distribution.

**Comment by JiaweiZhuang** [comment]
Thanks! Is the data file also available?

**Comment by zxdawn** [comment]
Maybe we can compare the result with 'True' value directly.

Since all methods are almost same for  0.1&deg; * 0.1&deg;.
We can regird data to 0.1&deg; * 0.1&deg; first and use `binned_statistic_2d` to sum for 1&deg; * 1&deg;.

**Comment by zxdawn** [comment]
> > `nearest_d2s` works fine.
> 
> That's good to know! I would appreciate a reproducible example (code + sample data). `nearest_d2s` is so rarely used so it is nice to show a use case.
> 
> > have you tried to calculate the cell area?
> 
> See this gist for now: https://gist.github.com/JiaweiZhuang/fc2f860133174523051260817e75a99d

I encountered some problems when installing xesmf from area branch:

It's successful when xesmf is installed on my machine:
`pip install --upgrade git+ssh://git@github.com/JiaweiZhuang/xESMF.git@area`
```
Branch area set up to track remote branch area from origin.
Switched to a new branch 'area'
Requirement already satisfied, skipping upgrade: esmpy in ./Software/anaconda3/lib/python3.6/site-packages (from xesmf==0.1.1) (7.1.0.dev0)
Requirement already satisfied, skipping upgrade: xarray in ./Software/anaconda3/lib/python3.6/site-packages (from xesmf==0.1.1) (0.11.0)
Requirement already satisfied, skipping upgrade: numpy in ./Software/anaconda3/lib/python3.6/site-packages (from xesmf==0.1.1) (1.15.4)
Requirement already satisfied, skipping upgrade: scipy in ./Software/anaconda3/lib/python3.6/site-packages (from xesmf==0.1.1) (1.1.0)
Requirement already satisfied, skipping upgrade: pandas>=0.19.2 in ./Software/anaconda3/lib/python3.6/site-packages (from xarray->xesmf==0.1.1) (0.23.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in ./Software/anaconda3/lib/python3.6/site-packages (from pandas>=0.19.2->xarray->xesmf==0.1.1) (2.6.1)
Requirement already satisfied, skipping upgrade: pytz>=2011k in ./Software/anaconda3/lib/python3.6/site-packages (from pandas>=0.19.2->xarray->xesmf==0.1.1) (2017.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./Software/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.19.2->xarray->xesmf==0.1.1) (1.11.0)
Building wheels for collected packages: xesmf
  Running setup.py bdist_wheel for xesmf ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-asry4otw/wheels/86/a4/73/9f5efeec79d3e63db519ba88566cc5b5f469dae1469a2d7e9b
Successfully built xesmf
Installing collected packages: xesmf
Successfully installed xesmf-0.1.1
```

However, I got error when installing it on hpc:
`pip install --upgrade git+ssh://git@github.com/JiaweiZhuang/xESMF.git@area`
```
Collecting git+ssh://git@github.com/JiaweiZhuang/xESMF.git@area
  Cloning ssh://git@github.com/JiaweiZhuang/xESMF.git (to revision area) to /tmp/pip-req-build-k16i3mzq
Branch 'area' set up to track remote branch 'area' from 'origin'.
Switched to a new branch 'area'
Collecting esmpy (from xesmf==0.1.1)
  Could not find a version that satisfies the requirement esmpy (from xesmf==0.1.1) (from versions: )
No matching distribution found for esmpy (from xesmf==0.1.1)
```
I checked the installed list by `conda list` on hpc and found `xesmf`:
`xesmf                     0.1.1                     <pip>
`
But, I couldn't remove it by `conda remove --force xesmf` or `pip uninstall xesmf`:
```
Solving environment: done

PackagesNotFoundError: The following packages are missing from the target environment:
  - xesmf
```
```
Skipping xesmf as it is not installed.
```

**Comment by JiaweiZhuang** [comment]
@zxdawn Install ESMPy with conda  `conda install -c conda-forge esmpy` and then install xESMF with pip. ESMPy is only installable from conda so pip cannot resolve the dependency.

**Comment by JiaweiZhuang** [comment]
Yes `ImportError: The ESMF shared library did not load properly.` is an ESMPy problem. Your HPC system probably has a separate ESMF library installed and dynamically linked, so ESMPy finds the incorrect installation of ESMF.

**Comment by zxdawn** [comment]
@JiaweiZhuang  How about the unit of `xe.util.cell_area`? I can't find it in the definition of [get_area()](http://www.earthsystemmodeling.org/esmf_releases/public/last/esmpy_doc/html/field.html?highlight=area#ESMF.api.field.Field.get_area) and [area()](http://www.earthsystemmodeling.org/esmf_releases/public/last/esmpy_doc/html/grid.html#ESMF.api.grid.Grid.area).
