### ISSUE TITLE
Cite this repo?

### ISSUE THREAD

**Issue by NicWayand** [JiaweiZhuang/xESMF#45]
Hi @JiaweiZhuang, I would like to cite this repo in my paper. Do you have a prefered citation?? My best guess was below.

@misc{Zhuang2018,
  author = {Zhuang, J.},
  title = {xESMF: Universal Regridder for Geospatial Data},
  year = {2018},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/JiaweiZhuang/xESMF}},
  commit = {c123a5bd574bf538844ea89bcb3528de3441a73e}
}

**Comment by JiaweiZhuang** [comment]
Great to hear that! You can cite zenodo DOI: http://doi.org/10.5281/zenodo.1134366

I should really write a paper on this to get more formal citations😊

**Comment by NicWayand** [comment]
Great thanks! Yes it would be highly cited!
