### ISSUE TITLE
regridder doesnt work 

### ISSUE THREAD

**Issue by mada0007** [JiaweiZhuang/xESMF#56]
I followed all the precedures on the installation page to install but the example i tried using xarray kills the kernel whenever I try and not sure why this is the. could you help explain why this is the case. 
When I try with Pycharm too I get these error messages

**Comment by JiaweiZhuang** [comment]
Could you post a [minimum reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports), including your environment setup? See [How to ask for help](https://xesmf.readthedocs.io/en/latest/#how-to-ask-for-help).
