### ISSUE TITLE
The best practice for sparse matrix multiplication

### ISSUE THREAD

**Issue by JiaweiZhuang** [JiaweiZhuang/xESMF#6]
Since #2 is largely solved, I've done some preliminary tests on sparse matrix multiplication (SMM), ~~using the [sparse](https://github.com/mrocklin/sparse) package.~~ Just realized the basic `scipy.sparse.coo_matrix.dot` is enough.

The test input data has the shape (600, 400, 10, 50), which is then regridded to shape (400, 300, 10, 50). The timing results are

- Calculating weights: **~14 s**
(This only needs to be done once, so I am not trying to optimize it)
~~- Applying weights with ESMPy: **1.46 s**~~
~~(transferring numpy data to ESMPy internal takes additional 6.6s, due to converting C-ordered array to Fortran-ordered)~~
~~- Applying weights with `sparse.tensordot()`: **579 ms**~~

~~It is quite surprising that `sparse.tensordot()`  is 3 times faster than ESMPy's internal Fortran routine.~~

- Applying weights: (The previous comparison was not fair. I've removed all unnecessary array copying and re-ordering, so here's the new timing)

| Method        | Applying weights        | Write output data to file |
| ------------- |-------------| -----|
| ESMPy    | 0.3 s <sup>[1]</sup> + 1 s <sup>[2]</sup> | 2 s <sup>[3]</sup> |
| coo_matrix.dot     | 600 ms  |  2 s |
| loop with numba      |  3 s   |  2 s | 
| loop with pure numpy | 6 s   |  2 s |

[1] : Passing input data to Fortran internal. It also doubles memory use, which is not a problem in other methods.
[2] : Actual SMM.
[3] : Output data doesn't duplicate memory.

The notebooks are available at
- [compute_weights.ipynb](../blob/master/examples/offline_weights/compute_weights.ipynb): offline weights generation and ESMPy SMM timing
- [apply_weights.ipynb](../blob/master/examples/offline_weights/apply_weights.ipynb): Python SMM timing

It might be useful to have both ESMPy and scipy as different backends. ESMPy results can be the reference. At least one non-ESMPy method is needed since ESMPy cannot reuse offline weights right now.

~~@bekozi If you have time (no hurry), could you run my notebooks to see whether it is true that ESMPy's SMM is slower than Python's? I want to make sure the comparison was fair and I was not using ESMPy in a wrong way.~~

---------------

This thread is for discussing the best practice for SMM (i.e. applying weights). 

Before developing high-level APIs I want to make sure I am using the most efficient way to perform SMM. Any suggestions will be appreciated. @mrocklin @pelson

**Comment by JiaweiZhuang** [comment]
Because the regridding is so fast even for this relatively large data, I will postpone #3 and focus on serial implementation first.

**Comment by mrocklin** [comment]
> It is quite surprising that sparse.tensordot() is 3 times faster than ESMPy's internal Fortran routine.

sparse.tensordot just calls `scipy.sparse.csr_matrix.dot`, which is written in C.  It is not surprising to see it perform decently.  There is some cost in converting from NDArray COO format to 2d CSR, but hopefully this is relatively small.  It is also cached if used repeatedly.

**Comment by mrocklin** [comment]
Is it necessary for ESMPy to write outputs to file or can it pass results back as numpy arrays?

**Comment by JiaweiZhuang** [comment]
> Is it necessary for ESMPy to write outputs to file or can it pass results back as numpy arrays?

Currently it has to write outputs to file. I don't know ESMPy internals so need to ask @bekozi

**Comment by JiaweiZhuang** [comment]
According to the timing tests, `scipy.sparse.coo_matrix.dot` should be the most efficient method to applying weights.
