### ISSUE TITLE
Need a test suite

### ISSUE THREAD

**Issue by jhamman** [JiaweiZhuang/xESMF#7]
Progress seems to be moving forward here quite nicely. I'm sensing a growing acknowledgement that the approach you are developing may be the path forward for many in the xarray/geoscience community. That said, to be fully adopted by the community, xESMF is going to need a comprehensive test suite. I'll suggest three key components:

1. Continuous integration (e.g. [TravisCI](https://travis-ci.org/))
2. Unit Tests (e.g. [pytest](https://docs.pytest.org/en/latest/))
3. Benchmarks (e.g. [asv](https://asv.readthedocs.io/en/latest/))

If you are not familiar with how to work with these tools, xarray is going to be a good reference and I think you'll find many of us are willing to chip in.

**Comment by JiaweiZhuang** [comment]
Thanks for the suggestions! That's definitely on my to-do list although currently I need to work on infrastructure things.

As for the benchmark, it would be good to refer to and compare with ESMF benchmark:
https://www.earthsystemcog.org/projects/esmf/performance (see any documents with "regrid" in the title).

**Comment by jhamman** [comment]
Just a quick follow up. I'd strongly encourage you not to wait until the package is complete before developing a test suite. From experience, waiting until you have a complete or even working package before writing tests usually ends in an incomplete test suite.

**Comment by JiaweiZhuang** [comment]
A test suite is now included in the latest version v0.1.1 ([codecov](https://codecov.io/gh/JiaweiZhuang/xESMF))

And I have to say thanks for this suggestion! Tests turn out to be extremely helpful when the package becomes more and more complicated...
