### ISSUE TITLE
Handle other generic axis names

### ISSUE THREAD

**Issue by pochedls** [JiaweiZhuang/xESMF#72]
Some CMIP files (mistakenly) use 'longitude' as an axis id (instead of lon). It would be useful to also handle "longitude" and "latitude" as axis ids. 

`regridder = xe.Regridder(trend_map, ds_out, 'bilinear', reuse_weights=True)`

>KeyError: 'lon'
> During handling of the above exception, another exception occurred:
> ...

In the meantime, is there a workaround for this issue (other than renaming the input axes)?

**Comment by JiaweiZhuang** [comment]
This coordinate naming issue is discussed in #38. A quick workaround by renaming coordinate is in #5

I was thinking about implementing a context manager to switch the naming, as detailed in https://github.com/JiaweiZhuang/xESMF/pull/38#issuecomment-432028269 Comment & PRs are highly welcome.

**Comment by pochedls** [comment]
@JiaweiZhuang - thank you for your fast response. Since this is a duplicate, I am closing this ticket. I'll take a closer look at the other issues and see if I am able to help with this. Thank you for putting this package together!
