### ISSUE TITLE
Retrieve regridding coverage

### ISSUE THREAD

**Issue by jorgsk** [JiaweiZhuang/xESMF#76]
I have a use-case where I'm regridding quantities that change geographically with time (e.g. a pollution plume in the atmosphere or in the ocean) from a finer to a coarser grid. If regridding for example 4 grid cells to 1, in the first timestep there might be 4 cells in the original grid that had a non nan/masked quantitiy, while in the second timestep only 1 cell has a non nan/masked quantitiy.

I would like to find a way to report a "coverage" for each timestep in the coarser grid. In the first timestep it should be 100 % for the mentioned cell, while in the second timestep it should be 25 %.

Is there a way to obtain this information?

**Comment by JiaweiZhuang** [comment]
If I understand correctly, you can set valid values to `1`, and set`nan` values to `0`. The conservative averaging result should be the fraction you want?

**Comment by jorgsk** [comment]
> If I understand correctly, you can set valid values to `1`, and set`nan` values to `0`. Then, the conservative averaging result should be the fraction you want?

That should work. Thanks!
