### ISSUE TITLE
Invoking xesmf with mpirun

### ISSUE THREAD

**Issue by nichannah** [JiaweiZhuang/xESMF#79]
I am using mpirun to run my Python program across multiple nodes in a cluster. Each instance of the program uses MPI to determine it's own rank and the number of processes but nothing else. Each program also uses xESMF to do some regridding. 

The problem is that the underlying ESMF library then tries to decompose the regridding task across the ranks. xESMF does not handle this and will have an error. 

Since xESMF does not support parallel regridding (yet) - is there a way to ensure that the underlying library does not try to do this? 

Any thoughts or work-around ideas would be much appreciated.

**Comment by JiaweiZhuang** [comment]
> Each instance of the program uses MPI to determine it's own rank and the number of processes but nothing else.

If you don't need any inter-process communication using [mpi4py](https://github.com/mpi4py/mpi4py) right? In that case I would suggest not using `mpirun` to launch your python script, but using a scheduler feature like [Slurm Job Array Support](https://slurm.schedmd.com/job_array.html) and get your job ID via `os.environ['SLURM_ARRAY_TASK_ID']`.

> Since xESMF does not support parallel regridding (yet)

Parallel weight construction is not supported yet, but the weights can be apply in parallel via Dask. See a long discussion at #3.

Does your use case actually need the MPI-style parallelization? If the data can be chunked in vertical/time dimension, Dask should be sufficient. Any reason for having to chunk in the horizontal?

**Comment by nichannah** [comment]
@JiaweiZhuang thank you for the very quick reply and useful suggestions.

Yes that is correct, the only reason to use MPI-style parallelization is to launch across multiple nodes. 

The SLURM suggestion is a good one, and this is what I'm doing on a cluster that has that installed. However I also need to get it running on a PBS cluster system which uses MPI to do task launching.

I have tried disconnecting the MPI communicator  (comm.Disconnect()) after start-up but in this seems to crash ESMF with a seg fault.

In this case I can't do vertical chunking because time points depend on each other.

**Comment by nichannah** [comment]
OK, I think you've answered this. The best approach is probably to use job arrays. An alternative might be use ESMF compiled without mpi support.
