### ISSUE TITLE
The concept of conservative regridding method

### ISSUE THREAD

**Issue by zxdawn** [JiaweiZhuang/xESMF#87]
I'm curious of the concept of `conservative` regridding: `area weighted` or `distance weighted`?
It seems that's `area weighted` in #17, right?

**Comment by JiaweiZhuang** [comment]
Yes it's area weighted. See https://climatedataguide.ucar.edu/climate-data-tools-and-analysis/regridding-overview and https://journals.ametsoc.org/doi/full/10.1175/1520-0493%281999%29127%3C2204%3AFASOCR%3E2.0.CO%3B2

**Comment by zxdawn** [comment]
@JiaweiZhuang Thanks!
